### ISSUE TITLE
FreeCAD 0.16 and higher

### ISSUE THREAD

**Issue by Richard-Haes-Ellis** [pgilfernandez/FreeCAD_stylesheets#5]
"If you use FreeCAD 0.16 or higher you don't need to download the stylesheets, they are bundled with official release." 

Where are the settings? How do you installe it? 

Many thanks

**Comment by amsheppard** [comment]
0.16 already has them included though I'm currently using 0.18/Win 10 x64. I was able to change it via:

Edit [menu] > Preferences [menu item] > General > General [tab] > Main window [section] > Style sheet: [drop down menu]

(Don't forget to restart FreeCAD after 'applying')
